name: CI

on:
  pull_request:
    branches: ['main']
    types: ['opened', 'reopened', 'synchronize']
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Force tests to run'
        required: false
        type: boolean

env:
  KUBECONFIG: /home/runner/.kube/config

permissions:
  contents: read

jobs:
  changes:
    name: Changes
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      helm: ${{ steps.filter.outputs.helm}}
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.0.2

      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.10.2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            helm:
              - 'helm/Chart.yaml'
              - 'helm/**/*'

  smoke:
    name: Smoke
    runs-on: ubuntu-22.04
    needs:
      - changes
    if: needs.changes.outputs.helm == 'true' || ${{ inputs.run_tests }}
    strategy:
      matrix:
        k8s: [v1.23.13, v1.24.7, v1.25.3, v1.26.0]
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.0.2

      - name: Create cluster
        run: |
          kind create cluster --kubeconfig ${KUBECONFIG} --image kindest/node:${{ matrix.k8s }}

      - name: Install chart
        env:
          WALLARM_API_TOKEN: ${{ secrets.WALLARM_API_TOKEN }}
        run: make helm-install

      - name: Run smoke tests
        env:
          KIND_CLUSTER_NAME: kind
          WALLARM_USER_UUID: ${{ secrets.WALLARM_API_USER_UUID }}
          WALLARM_USER_SECRET: ${{ secrets.WALLARM_API_USER_SECRET }}
          WALLARM_CLIENT_ID: 4
        run: |
          echo ${{ secrets.GITLAB_TOKEN_SECRET }} | docker login -u ${{ secrets.GITLAB_TOKEN_NAME }} --password-stdin dkr.wallarm.com
          make smoke-test

  helm-install:
    name: Helm install
    runs-on: ubuntu-22.04
    needs:
      - changes
    if: needs.changes.outputs.helm == 'true' || ${{ inputs.run_tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.0.2

      - name: Create cluster
        run: kind create cluster --kubeconfig ${KUBECONFIG} --image kindest/node:v1.24.7

      - name: Run chart tests
        env:
          WALLARM_API_TOKEN: ${{ secrets.WALLARM_API_TOKEN }}
        run: make helm-test
