name: Publish Helm

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    runs-on: self-hosted-1cpu
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Import secrets
        uses: hashicorp/vault-action@130d1f5f4fe645bb6c83e4225c04d64cfb62de6e # v2.5.0
        id: secrets
        with:
          exportEnv: false
          url: ${{ secrets.VAULT_URL }}
          role: ${{ secrets.VAULT_ROLE }}
          method: kubernetes
          secrets: |
            kv-gitlab-ci/data/github/shared/github_token token | GITHUB_TOKEN

      - name: Extract chart and app versions
        run: |
          echo "CHART_VERSION=$(yq -r '.version' helm/Chart.yaml)" >> $GITHUB_ENV
          echo "APP_VERSION=$(yq -r '.appVersion' helm/Chart.yaml)" >> $GITHUB_ENV

      - name: Publish
        uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260 # master
        with:
          token: ${{ steps.secrets.outputs.GITHUB_TOKEN }}
          charts_dir: .
          charts_url: https://charts.wallarm.com
          linting: off
          repository: helm-charts
          branch: main
          target_dir: oob-ebpf
          index_dir: .
          app_version: ${{ env.APP_VERSION }}
          chart_version: ${{ env.CHART_VERSION }}